# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v7
    
    - name: Set up uv w/ Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        version: "latest"
        python-version: ${{ matrix.python-version }}
    
    - name: Build
      run: |
        uv sync --frozen --all-extras
        uv build
    
    - name: Test with pytest
      env:
        HORNET_PHPSESSID: ${{secrets.HORNET_PHPSESSID}}
        LOW_PHPSESSID: ${{secrets.LOW_PHPSESSID}}
        LOW_USERNAME: ${{secrets.LOW_USERNAME}}
        LOW_PASSWORD: ${{secrets.LOW_PASSWORD}}
        SKIP_HEAVY_TESTS: true
        SUPPRESS_LOGS: true
      run: |
        uv run --frozen pytest
    

